workflows:
  my-workflow:
    name: lambda test
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Unit tests
        script: |
          mkdir -p test-results
          flutter test test --machine > test-results/flutter.json     
        test_report: test-results/flutter.json
      - name: Set up key properties
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH   # Not required if using team code signing identities
          cat >> "$CM_BUILD_DIR/how-to-publish-flutter-apps-to-playstore/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF          
      - name: Build APK with Flutter
        script: |
                    cd . && flutter build apk --release
    artifacts:
      - build/**/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - clsyfriday@gmail.com
    