name: code_magic_test
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  http: ^0.13.4
  stream_transform: ^2.0.0
  bloc_concurrency: ^0.2.0
  url_launcher: ^6.0.20
  bloc_test: ^9.0.3
  mocktail: ^0.3.0
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  integration_test:
   sdk: flutter  
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: "assets/launchericon_codemagic.png"

flutter:
  uses-material-design: true
  assets:
     - assets/
